name = "Diagonalizations"
uuid = "9cd687f3-b62d-43f3-8fd3-ffcd9e581047"
authors = ["Marco-Congedo <marco.congedo@gmail.com>"]
version = "0.2.5"

[deps]
CovarianceEstimation = "587fd27a-f159-11e8-2dae-1979310e6154"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
PosDefManifold = "f45a3650-5c51-11e9-1e9a-133aa5e309cf"
PrecompileSignatures = "91cefc8d-f054-46dc-8f8c-26e11d7c5411"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
CovarianceEstimation = "0.2"
LaTeXStrings = "1.2, 1.3, 1.4"
LinearAlgebra = "1.11"
Parsers = "2.6, 2.7, 2.8"
PosDefManifold = "0.4, 0.5"
PrecompileSignatures = "3.0.3"
PrettyTables = "2.2, 2.3, 2.4"
Statistics = "1.11"
StatsBase = "0.32, 0.33, 0.34"
StatsPlots = "0.15"
Weave = "0.10"
julia = "1"

[extras]
LinearAlgebra = "621f4979-c628-5d54-868e-fcf4e3e8185c"
PosDefManifold = "f45a3650-5c51-11e9-1e9a-133aa5e309cf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["PosDefManifold", "Statistics", "LinearAlgebra", "Test"]
